export {default as Root} from "./Root"
export {default as Home} from "./Home"
export {default as News} from "./News"
export {default as Coin} from "./Coin"
export {default as Coins} from "./Coins"
export {default as Portfolio} from "./Portfolio"